name: Publish

on:
  release:
    types: [ published ]

jobs:
  nuget:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ref that triggered workflow
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7'

      - name: Fetch Latest .nupkg
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: "tags/${{ github.ref_name }}"
          file: "tcli.${{ github.ref_name }}.nupkg"
          target: "tcli.nupkg"

      - name: Publish to NuGet
        shell: bash
        run: dotnet nuget push tcli.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
